/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.example.demo.util;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.example.demo.entity.Holiday;
import com.example.demo.util.HolidayUtil;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class HolidayUtil_SSTest extends HolidayUtil_SSTest_scaffolding {
// allCoveredLines:[10, 40, 41, 76, 80, 82]

  @Test(timeout = 4000)
  public void test_getMonthHoliday_0()  throws Throwable  {
      //caseID:af8474518ce1bd5e9953e03d11df0d53
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
        try {
          //CoveredLines: [10, 40, 41, 76, 80, 82]
          //Input_0_Integer: 0
          //Input_1_Integer: 0
          //Assert: assertTrue(method_result.isEmpty());
          
          HolidayUtil holidayUtil0 = new HolidayUtil();
          Integer integer0 = new Integer(0);
          
          //Call method: getMonthHoliday
          List<Holiday> list0 = HolidayUtil.getMonthHoliday(integer0, integer0);
          
          //Test Result Assert
          assertTrue(list0.isEmpty());
        } catch(Throwable t) {
        }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }
}
