/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.example.demo.service;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.example.demo.service.ServiceDemo;
import java.util.LinkedList;
import java.util.List;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class ServiceDemo_SSTest extends ServiceDemo_SSTest_scaffolding {
// allCoveredLines:[5, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 20, 23, 26, 27, 28, 30, 31]

  @Test(timeout = 4000)
  public void test_ifElseMethod_0()  throws Throwable  {
      //caseID:bb9fab0fee445cc6b93c3911ee424394
      //CoveredLines: [5, 8, 23]
      //Input_0_Integer: null
      //Assert: assertNull(method_result);
      
      ServiceDemo serviceDemo0 = new ServiceDemo();
      
      //Call method: ifElseMethod
      String string0 = serviceDemo0.ifElseMethod((Integer) null);
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test_ifElseMethod_1()  throws Throwable  {
      //caseID:82499dbbdca887e07f34d0332d952aee
      //CoveredLines: [5, 8, 9, 10, 11]
      //Input_0_Integer: 5
      //Assert: assertEquals("juvenile", method_result);
      //Assert: assertNotNull(method_result);
      
      ServiceDemo serviceDemo0 = new ServiceDemo();
      Integer integer0 = new Integer(5);
      
      //Call method: ifElseMethod
      String string0 = serviceDemo0.ifElseMethod(integer0);
      
      //Test Result Assert
      assertEquals("juvenile", string0);
      
      //Test Result Assert
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test_ifElseMethod_2()  throws Throwable  {
      //caseID:28f37f0054f8d7927d59cf116ccc63cf
      //CoveredLines: [5, 8, 9, 12, 13, 14]
      //Input_0_Integer: 25
      //Assert: assertNotNull(method_result);
      //Assert: assertEquals("youth", method_result);
      
      ServiceDemo serviceDemo0 = new ServiceDemo();
      Integer integer0 = new Integer(25);
      
      //Call method: ifElseMethod
      String string0 = serviceDemo0.ifElseMethod(integer0);
      
      //Test Result Assert
      assertNotNull(string0);
      
      //Test Result Assert
      assertEquals("youth", string0);
  }

  @Test(timeout = 4000)
  public void test_ifElseMethod_3()  throws Throwable  {
      //caseID:95189ecacce68574c6c74661003c3e3a
      //CoveredLines: [5, 8, 9, 12, 15, 16, 17]
      //Input_0_Integer: 120
      //Assert: assertEquals("middle-aged", method_result);
      //Assert: assertNotNull(method_result);
      
      ServiceDemo serviceDemo0 = new ServiceDemo();
      Integer integer0 = new Integer(120);
      
      //Call method: ifElseMethod
      String string0 = serviceDemo0.ifElseMethod(integer0);
      
      //Test Result Assert
      assertEquals("middle-aged", string0);
      
      //Test Result Assert
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test_ifElseMethod_4()  throws Throwable  {
      //caseID:c4ebce8b57d188155688e0dd13544453
      //CoveredLines: [5, 8, 9, 12, 15, 19, 20]
      //Input_0_Integer: 0
      //Assert: assertNotNull(method_result);
      //Assert: assertEquals("error", method_result);
      
      ServiceDemo serviceDemo0 = new ServiceDemo();
      Integer integer0 = new Integer(0);
      
      //Call method: ifElseMethod
      String string0 = serviceDemo0.ifElseMethod(integer0);
      
      //Test Result Assert
      assertNotNull(string0);
      
      //Test Result Assert
      assertEquals("error", string0);
  }

  @Test(timeout = 4000)
  public void test_ifElseMethod_5()  throws Throwable  {
      //caseID:99547813b5532b86ae27b66412a06dda
      //CoveredLines: [5, 8, 9, 12, 15, 19, 20]
      //Input_0_Integer: 171
      //Assert: assertNotNull(method_result);
      //Assert: assertEquals("error", method_result);
      
      ServiceDemo serviceDemo0 = new ServiceDemo();
      Integer integer0 = new Integer(171);
      
      //Call method: ifElseMethod
      String string0 = serviceDemo0.ifElseMethod(integer0);
      
      //Test Result Assert
      assertNotNull(string0);
      
      //Test Result Assert
      assertEquals("error", string0);
  }

  @Test(timeout = 4000)
  public void test_whileMethod_6()  throws Throwable  {
      //caseID:419e37c21d6cc88d7137cb513988e76d
      //CoveredLines: [5, 26, 27, 28]
      //Input_0_List<String>: linkedList0
      //Assert: assertNotNull(method_result);
      //Assert: assertEquals("hello", method_result);
      
      ServiceDemo serviceDemo0 = new ServiceDemo();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      
      linkedList0.add("hello");
      
      //Call method: whileMethod
      String string0 = serviceDemo0.whileMethod(linkedList0);
      
      //Test Result Assert
      assertNotNull(string0);
      
      //Test Result Assert
      assertEquals("hello", string0);
  }

  @Test(timeout = 4000)
  public void test_whileMethod_7()  throws Throwable  {
      //caseID:1291ea8bdf8f6e145e83359656b65c3c
      //CoveredLines: [5, 26, 27, 30, 31]
      //Input_0_List<String>: linkedList0
      //Assert: assertNull(method_result);
      
      ServiceDemo serviceDemo0 = new ServiceDemo();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      
      linkedList0.add("1.0");
      
      //Call method: whileMethod
      String string0 = serviceDemo0.whileMethod(linkedList0);
      
      //Test Result Assert
      assertNull(string0);
  }
}
