/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.example.demo.service;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.example.demo.service.ServiceDemo;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class ServiceDemo_SSTest extends ServiceDemo_SSTest_scaffolding {
// allCoveredLines:[3, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 21]

  @Test(timeout = 4000)
  public void test_ifElseMethod_0()  throws Throwable  {
      //caseID:26a7c8a1b17bad26c0b5b73d20277a69
      //CoveredLines: [3, 6, 21]
      //Input_0_Integer: null
      //Assert: assertNull(method_result);
      
      ServiceDemo serviceDemo0 = new ServiceDemo();
      
      //Call method: ifElseMethod
      String string0 = serviceDemo0.ifElseMethod((Integer) null);
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test_ifElseMethod_1()  throws Throwable  {
      //caseID:555579c4d9c6e25c0eab395cad752ea0
      //CoveredLines: [3, 6, 7, 8, 9]
      //Input_0_Integer: 18
      //Assert: assertEquals("juvenile", method_result);
      //Assert: assertNotNull(method_result);
      
      ServiceDemo serviceDemo0 = new ServiceDemo();
      Integer integer0 = new Integer(18);
      
      //Call method: ifElseMethod
      String string0 = serviceDemo0.ifElseMethod(integer0);
      
      //Test Result Assert
      assertEquals("juvenile", string0);
      
      //Test Result Assert
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test_ifElseMethod_2()  throws Throwable  {
      //caseID:16c294194e510dbd9b96673a38eca7b4
      //CoveredLines: [3, 6, 7, 10, 11, 12]
      //Input_0_Integer: 25
      //Assert: assertEquals("youth", method_result);
      //Assert: assertNotNull(method_result);
      
      ServiceDemo serviceDemo0 = new ServiceDemo();
      Integer integer0 = new Integer(25);
      
      //Call method: ifElseMethod
      String string0 = serviceDemo0.ifElseMethod(integer0);
      
      //Test Result Assert
      assertEquals("youth", string0);
      
      //Test Result Assert
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test_ifElseMethod_3()  throws Throwable  {
      //caseID:cc8730b885fd2b9e54a267c61ea26eb0
      //CoveredLines: [3, 6, 7, 10, 13, 14, 15]
      //Input_0_Integer: 120
      //Assert: assertNotNull(method_result);
      //Assert: assertEquals("middle-aged", method_result);
      
      ServiceDemo serviceDemo0 = new ServiceDemo();
      Integer integer0 = new Integer(120);
      
      //Call method: ifElseMethod
      String string0 = serviceDemo0.ifElseMethod(integer0);
      
      //Test Result Assert
      assertNotNull(string0);
      
      //Test Result Assert
      assertEquals("middle-aged", string0);
  }

  @Test(timeout = 4000)
  public void test_ifElseMethod_4()  throws Throwable  {
      //caseID:a626abd3c7955e39b34098ee2f891cf9
      //CoveredLines: [3, 6, 7, 10, 13, 17, 18]
      //Input_0_Integer: 0
      //Assert: assertEquals("error", method_result);
      //Assert: assertNotNull(method_result);
      
      ServiceDemo serviceDemo0 = new ServiceDemo();
      Integer integer0 = new Integer(0);
      
      //Call method: ifElseMethod
      String string0 = serviceDemo0.ifElseMethod(integer0);
      
      //Test Result Assert
      assertEquals("error", string0);
      
      //Test Result Assert
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test_ifElseMethod_5()  throws Throwable  {
      //caseID:d3cca80b4b5d6b5d29419ad9c18826f9
      //CoveredLines: [3, 6, 7, 10, 13, 17, 18]
      //Input_0_Integer: 418
      //Assert: assertEquals("error", method_result);
      //Assert: assertNotNull(method_result);
      
      ServiceDemo serviceDemo0 = new ServiceDemo();
      Integer integer0 = new Integer(418);
      
      //Call method: ifElseMethod
      String string0 = serviceDemo0.ifElseMethod(integer0);
      
      //Test Result Assert
      assertEquals("error", string0);
      
      //Test Result Assert
      assertNotNull(string0);
  }
}
